### PR TITLE
exmaple to connecting obsidian and svelte together

### PR DESCRIPTION
**Pull request by aptend**
this is just my solution, how do you think

### CODE REVIEW

**Comment by aptend** [comment]
@caasion I connect Svelte and CodeMirror, and implement some basic components, if you feel ok please merge it and work on top of it

**Comment by caasion** [comment]
btw I'm not sure if it is something you have done in these commits, but I wasn't able to start the plugin after I complied it.

image

Good work on getting started though. If this is your first time with svelte then you learn way to quick lol :dizzy_face:.

**Comment by aptend** [comment]
A bug happens if there is no `data.json` in the plugin directory. It is fixed already in the main and svelte branches.

**Comment by aptend** [comment]
yeah, it is my first time with svelt, but I tried React before and that teaches me a lot 😉

**Pull request merged**
